### ISSUE TITLE
Document ability to test HTTP response headers

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#19]
Smoketest can test HTTP response headers in check directives. I looked through <https://github.com/usnews/smoketest/tree/9bab913c2712abf628b113e5720f57f9e8f23768/docs/source> and I don't think we currently have this functionality documented.

**Comment by malerichc** [comment]
I filed https://github.com/usnews/smoketest/pull/20, feel free to leave feedback!

**Comment by mcbridem** [comment]
Sweet, thanks again!
