### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#4]
Smoketest should run using Python 3. We currently specify that Python 2.7 is required.

**Comment by bpeebles** [comment]
Is the intention to become Python 3.x only or to support both 2.7 and 3.x using something like https://pypi.python.org/pypi/six or https://pypi.python.org/pypi/nine as required? If so, getting https://pypi.python.org/pypi/tox set up as part of this ticket or another related one maybe very helpful.

**Comment by mcbridem** [comment]
If we can support both Python 2 and Python 3, I think that would be great.

**Comment by mcbridem** [comment]
Neat! Thanks for all the work on this.
